blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Need Help?
    url: https://github.com/CYBERCLAN237/REJOINDRE-XYBERCLAN/discussions
    about: If you have questions about the joining process, please use our discussions board.
